version: 2.0
jobs:
  build:
    docker:
      - image: burgerdev/ocaml-addressmapper-devel:alpine
    working_directory: /tmp/oam
    steps:
      - checkout
      - run:
          name: "Build"
          command: |
            export TERM=dumb
            eval `opam config env`
            make build
      - run:
          name: "Test"
          command: |
            export TERM=dumb
            eval `opam config env`
            make test
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
